name: test

on:
  push:
    branches:
    - 'main'
  pull_request:

jobs:
  gcloud:
    name: test-setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@tequilarista-retire-cruft
    - run: gcloud info
    - run: gcloud info
    - run: which gcloud
  gcloud-old:
    name: test-setup-gcloud-old
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@tequilarista-retire-cruft
    - run: gcloud info
    - run: which gcloud
